name: Deploy Geralt Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            PROJECT_DIR="${{ secrets.PATH_BOT }}"
            REPO_URL="${{ secrets.GIT_URL }}"

            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "üìÅ Initializing repo..."

              cd "$PROJECT_DIR"
              git init
              git remote add origin "$REPO_URL"
              git fetch origin main
              git reset --hard origin/main
            else
              echo "üîÑ Update rep..."
              cd "$PROJECT_DIR"
              git fetch origin main
              git reset --hard origin/main
            fi

            cd $PROJECT_DIR
            mkdir -p ./Data

            echo "üßπ Cleaning Docker system..."
            docker system prune -af

            echo "üê≥ Restarting Docker containers..."
            docker compose down
            docker compose up -d --build

            echo "‚úÖ Deployment completed successfully!"